feat: implement issuer and certificaterequest api and controllers
dana-team/cert-external-issuer pull request #1
Opened 2024-07-06 11:42 UTC by mzeevi

This PR includes all the code needed for the external issuer, with the exception of the actual signing of the CSR generated by cert-manager.

2024-08-07 11:33 UTC, arielsepton commented on internal/setup/controllers.go
> +		return "", errors.New("not running in-cluster")
```suggestion
		return "", errNotInCluster
```

2024-08-08 06:54 UTC, arielsepton requested changes
Everything looks excellent. I would suggest adding tests for `internal/issuer/validate/validate.go`, but I trust your judgment on this. I've left a few minor comments.

2024-08-10 04:58 UTC, mzeevi commented
Thanks for the review, I've pushed the changes. As for the missing tests, I'll open issues with some stuff that need to be done so others can get into this code.

2024-08-11 06:41 UTC, arielsepton approved these changes
/lgtm

2024-08-12 06:48 UTC, merged